go_import_path: github.com/minio/minio

os: linux
arch: ppc64le
dist: focal
sudo: required
language: go
go:
- "1.16.x"
env:
     - ARCH=ppc64le CGO_ENABLED=0 GO111MODULE=on

addons:
  apt:
    packages:
    - shellcheck
    - jq
    
services:
  - docker
  
before_install:
  - nvm install stable

before_script:
  - git clone --depth 1 https://github.com/minio/minio.git
  - cd minio
  #- git checkout 8ae9f75d6daee8409a11bd50070be42739107db3
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

script:
  - make
  - diff -au <(gofmt -s -d cmd) <(printf "")
  - diff -au <(gofmt -s -d pkg) <(printf "")
  - travis_wait for d in $(go list ./... | grep -v browser); do CGO_ENABLED=1 go test -v --timeout 20m "$d"; done
  - make verifiers
  - make crosscompile
  - ./minio --version


notifications:
  slack:
    rooms:
      - secure: "OmLuBvxMiay2sBLY5cEse9DMl7nZGxXllwR5Xz4x9G5f8L6sKvtlpQPXyagAh2c7yf7b50rQBrwb4/w1GXtO/mgbhlNZhb94eNzeCq+hAB5ApLMbtoACk+TlniOSuCNEch8X/2usgQDKZDKiAqk62uVmzhvWHkZqq9b/s5gicpa80skVfsNvpCCf9lFNeNAMMayDbUWq0qdExvLDfwWOesB8D8nY7qXdJcjCzJVqWK0GWdoUAKNkRNNWf/zcMIVgajJa1s9g2F6FZfBVE2qDtHJyMmbCpncxjcirFTq8CbHwuRslAYeLGSQX03Zt0RlD7GDywl2ilOX2kze0FOqCJ0fH4m/l3Q7UaJ34ON3X5+/KIlq8cNZiTtjM3HAfxOZ/8IY7ajAOduUMGuYmhDN18NTneY4uFMOqwRcaQIPglIoE3tv8LybPmO7dzKNLmUir1yKYUpYrc/oL8Z0bW3VhPJIXyavsTHZeI6B7WQ2/rS3psaY5Blxav0N43Vjf81hJvV/bYuN0ZVijmT0RWem254UGT4R13e33q1VNxL987oahOu/rcWHp1q+XQJLxLKrAS5QQbidwnYZ7KGZ/a/cKRh3HgawJFbwc/379Dlm7XWQWiHO0Bhh7Prl+WsxWDeY1OIdpfHDPxRhNldq+9YO1GV6cy1zk1X6de9is6uDxlEI="
    on_success: change
    on_failure: change
