go_import_path: github.com/minio/minio

language: go

addons:
  apt:
    packages:
    - shellcheck

branches:
  only:
    - master

os: linux-ppc64le
dist: trusty
sudo: required
env: ARCH=ppc64le CGO_ENABLED=0 GO111MODULE=on SIMPLE_CI=1

go: 1.13.x

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [[ "${TRAVIS_OS_NAME}" == "linux-ppc64le" ]]; then sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'; fi

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]]; then nvm install stable ; fi
  
script:
  - make
  - diff -au <(gofmt -s -d cmd) <(printf "")
  - diff -au <(gofmt -s -d pkg) <(printf "")
  - make test-race
  - make crosscompile
  - make verify
  - cd browser && npm install && npm run test && cd ..
  - bash -c 'shopt -s globstar; shellcheck mint/**/*.sh'
